In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset.csv")
df.head

<bound method NDFrame.head of       No  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0      1            6      148             72             35        0  33.6   
1      2            1       85             66             29        0  26.6   
2      3            8      183             64              0        0  23.3   
3      4            1       89             66             23       94  28.1   
4      5            0      137             40             35      168  43.1   
..   ...          ...      ...            ...            ...      ...   ...   
763  764           10      101             76             48      180  32.9   
764  765            2      122             70             27        0  36.8   
765  766            5      121             72             23      112  26.2   
766  767            1      126             60              0        0  30.1   
767  768            1       93             70             31        0  30.4   

     DiabetesPedigree

In [3]:
d = np.array(df)[:, :-1]
print("The attributes are: ", d)

The attributes are:  [[1.00e+00 6.00e+00 1.48e+02 ... 3.36e+01 6.27e-01 5.00e+01]
 [2.00e+00 1.00e+00 8.50e+01 ... 2.66e+01 3.51e-01 3.10e+01]
 [3.00e+00 8.00e+00 1.83e+02 ... 2.33e+01 6.72e-01 3.20e+01]
 ...
 [7.66e+02 5.00e+00 1.21e+02 ... 2.62e+01 2.45e-01 3.00e+01]
 [7.67e+02 1.00e+00 1.26e+02 ... 3.01e+01 3.49e-01 4.70e+01]
 [7.68e+02 1.00e+00 9.30e+01 ... 3.04e+01 3.15e-01 2.30e+01]]


In [17]:
target = np.array(df)[:, -1]
print("The target is: ", target)

The target is:  [1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0.
 1. 1. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1.
 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.
 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1.
 0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0.
 1. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1

In [18]:
def train(c,t) :
    for i, val in enumerate(t):
        if val == 1:
            specific_hypothesis = c[i].copy()
            break
    for i, val in enumerate(c): 
        if t[i] == 1:
            for x in range(len(specific_hypothesis)): 
                if val[x] != specific_hypothesis[x]:
                    specific_hypothesis[x] = -1
                else:
                    pass
    final_hypothesis = []
    for ele in specific_hypothesis:
        if ele == -1:
            final_hypothesis.append("?")
        else:
            final_hypothesis.append(ele)
    return final_hypothesis
print(" The final hypothesis is:", train(d,target))

 The final hypothesis is: ['?', '?', '?', '?', '?', '?', '?', '?', '?']
